### ISSUE TITLE
Create a user management page for Tunnelbeast

### ISSUE THREAD

**Issue by shix16** [bahusvel/TunnelBeast#9]
Create a user management page for Tunnelbeast

**Comment by bahusvel** [comment]
LDAP user management is not within scope of TunnelBeast, it should be left up to another software. I found some simple management portal that you may use:
- https://oss.gonicus.de/labs/gosa/
- https://github.com/futurice/futurice-ldap-user-manager
- https://www.ldap-account-manager.org/lamcms/
- http://phpldapadmin.sourceforge.net/wiki/index.php/Main_Page
- http://www.linid.org/welcome/index.html

Try them out, let me know which one worked best.
